### ISSUE TITLE
Support x509.ExtKeyUsageClientAuth

### ISSUE THREAD

**Issue by vjanelle** [choria-io/go-security#15]
Our mTLS certificates have the x509.ExtKeyUsageClientAuth field set.  Crypto/TLS won't validate certificates unless told to accept it.

**Comment by ripienaar** [comment]
weird thing is the puppet ones also have it, so wy does it work with them:

```
$ openssl x509 -in /home/rip/.puppetlabs/etc/puppet/ssl/certs/rip.mcollective.pem -text
....
            X509v3 Extended Key Usage: critical
                TLS Web Server Authentication, TLS Web Client Authentication
....
```

**Comment by vjanelle** [comment]
The certificates I'm using *only* have the client auth set.

**Comment by vjanelle** [comment]
@ripienaar guess I should've started with the error message(output from `choria server`):

```
WARN[0004] Certificate does not pass verification as '': x509: certificate specifies an incompatible key usage: leaf contains the following, recognized EKUs: 1.3.6.1.5.5.7.3.2, 1.3.6.1.5.5.7.3.7  component=security ssl=file
WARN[0004] Received certificate 'XXX' certiicate did not pass verification: x509: certificate specifies an incompatible key usage: leaf contains the following, recognized EKUs: 1.3.6.1.5.5.7.3.2, 1.3.6.1.5.5.7.3.7  component=security ssl=file
```

http://oid-info.com/get/1.3.6.1.5.5.7.3.2 (client auth)
http://oid-info.com/get/1.3.6.1.5.5.7.3.7 (ipsec user) (not sure why we set this)

**Comment by vjanelle** [comment]
@ripienaar if you don't specify *any* ext key usages, then it'll default to using ExtKeyUsageServerAuth:

https://github.com/golang/go/blob/3813edf26edb78620632dc9c7d66096e5b2b5019/src/crypto/x509/verify.go#L771-L774

Could probably make this configurable.
