### ISSUE TITLE
go-security filesec should validate before trying to cache

### ISSUE THREAD

**Issue by vjanelle** [choria-io/go-security#16]
If you change the whitelists, go-security filesec will reference a cached item and not check the identity in the future.

**Comment by ripienaar** [comment]
Not clear why this is a problem? Can you elaborate?

**Comment by vjanelle** [comment]
@ripienaar if you change the values of `plugin.choria.security.certname_whitelist`, previously cached certificates will still be allowed through until they're removed from the cache.

**Comment by ripienaar** [comment]
Thank you @vjanelle
