### ISSUE TITLE
support regex enclosed in slashes for certname_whitelist config

### ISSUE THREAD

**Issue by rjd1** [choria-io/go-security#22]
To maintain consistency with mcollectived config, the regex string for this option should work with or without surrounding forward slashes. E.g.: 

`plugin.choria.security.certname_whitelist = /\.mcollective$/, /\.mco$/`

or

`plugin.choria.security.certname_whitelist = \.mcollective$, \.mco$`

Currently only the latter works.

**Comment by ripienaar** [comment]
Need to expand this code:

https://github.com/choria-io/go-security/blob/9c90c6ebc9548a8300fff479716bad9c739d6717/filesec/util.go#L10

to be more like this code:

https://github.com/choria-io/mcollective-choria/blob/13db0c473d6fc91218db5d1d49f75d61bfb833f3/lib/mcollective/security/choria.rb#L281
