### ISSUE TITLE
while caching data privilged certs are validated with callerid

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-security#27]
When determining if a certificate has to be cached we first check its signed by the CA then if its privileged:

https://github.com/choria-io/go-security/blob/6440c9b8406c0f45440a8da5bacad016097f00f9/filesec/file_security.go#L631-L639

Here though `name` would be the callerid not the name found in the certificate, we need to parse the certificate and check it using its `cert.Subject.CommonName`.

**Comment by ripienaar** [comment]
@vjanelle curious about your thoughts here, how would your dns alt names place into this? Would we check first if there are alt names and check each and then finally the common name?

**Comment by ripienaar** [comment]
So from above I reckon if we pulled out `cert.Subject.Common` as now and also `cert.DNSNames` we can check the whole lot and if any of its is privilged we treat the cert as privilged and save it as that name

this way you can issue certs with your usual names and DNS name in the privilged part, what do you think @vjanelle ?

**Comment by vjanelle** [comment]
What happens if two certs have the same name in a SAN?

**Comment by ripienaar** [comment]
I would do this loop only while specifically checking for privileged names - past that I only take the callername as it is now
