### ISSUE TITLE
email sans in client certificates are not parsed correctly

### ISSUE THREAD

**Issue by traylenator** [choria-io/go-security#34]
choria 0.10.

With client certificates containing a subject alternate name of email. e.g.

```
           X509v3 Subject Alternative Name: 
                othername:<unsupported>, email:steve@example.ch
```
the choria server always fails to parse and validate this correctly and results in 

```
{"level":"error","msg":"Could not cache Client Certificate: certificate 'email' did not pass validation","time":"2019-04-12T17:16:28+02:00"}
```

https://golang.org/src/crypto/x509/verify.go  line 756  all SANs are assumed to be DNSnames.

**Comment by traylenator** [comment]
Was asked to include @vjanelle

**Comment by traylenator** [comment]
The particular error was after updating the ruby client to accept
```
MCOLLECTIVE_CERTNAME='email:steve@example.ch' mco ping
```

**Comment by vjanelle** [comment]
Thanks!  Can you include steps for making your certs?  I can figure it out, but would save time.

**Comment by ripienaar** [comment]
sorry for missing this one, added it to my board for next release

**Comment by traylenator** [comment]
@vjanelle our certificates are created by some microsoft product.

**Comment by ripienaar** [comment]
Suspect we'll need to do something in the ruby code as well to make this work sanely, but I merged this one anyway and will be released in choria today
