### ISSUE TITLE
Create a generic rego evaluator

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-security#62]
We have rego now in mcorpc and in aaasvc, we have a fairly solid idea of how this will look for choria so we can probably extract out something generic before we take next steps:

 * rego evaluation in provisioning server
 * possibly in federation broker to control routing decisions

The basic things we need are:

 * send in inputs in a `map[string]interface{}`
 * query to run
 * module name
 * supply optional functions
 * configure path to the rego file to use OR supply the rego file as bytes
 * configure tracing or not

Something like:

`pass, err := thing.Evaluate(inputs, logger, File(f), Trace())`

or

`pass, err := thing.Evaluate(inputs, logger, Policy(p), Trace())`

And error I guess have to be something like rego errors with extra context associated

We'd also have a configuration `Functions(f)` which would take a function map to add to the rego runtime like aaasvc does.

This would be rego specific, i dont really have the appetite now to make a whole abstraction that can support other forms of policy engine.

What do you think @vjanelle

**Comment by vjanelle** [comment]
The only thing I can think of is the loader interface - supplying either the bytes or paths would need to be different options.

Also, we should initialize OPA in the init function, not on every request.  This may need some context handling.

**Comment by vjanelle** [comment]
Multiple bindings might also something to look at, beyond just only having 'allow'.
